# Generated by Django 3.0.3 on 2020-02-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='task_list',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modules.TaskList'),
        ),
        migrations.AlterField(
            model_name='module',
            name='video_link',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
