# Generated by Django 3.0.3 on 2020-02-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20200224_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='module_list',
        ),
        migrations.RemoveField(
            model_name='module',
            name='task_list',
        ),
        migrations.RemoveField(
            model_name='task',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='task_list',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ManyToManyField(related_name='modules', to='modules.Course'),
        ),
        migrations.AddField(
            model_name='task',
            name='module',
            field=models.ManyToManyField(related_name='tasks', to='modules.Module'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
