# Generated by Django 3.0.3 on 2020-02-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20200222_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.TaskList'),
        ),
    ]
