# Generated by Django 3.0.3 on 2020-02-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20200224_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
