# Generated by Django 3.0.3 on 2020-02-24 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_delete_tasklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='modules.Course'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='module',
        ),
        migrations.AddField(
            model_name='task',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='modules.Module'),
        ),
    ]
